version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app   # для разработки: изменения в коде сразу отражаются в контейнере
    environment:
      - PYTHONUNBUFFERED=1